### ISSUE TITLE
Warning message from HWLOC library in windows OS on system with more than 32 cores per socket

### ISSUE THREAD

**Issue by rppendya** [open-mpi/hwloc#497]
### What version of hwloc are you using?

2.5.0

### Which operating system and hardware are you running on?

Windows. Intel(R) Xeon(R) Platinum 8360Y

### Details of the problem
HWLOC is showing a warning message on windows OS on system with more than 32 cores per socket. Following is the warning message.

****************************************************************************
* hwloc 2.5.0 received invalid information from the operating system.
*
* Failed with: intersection without inclusion
* while inserting Group0 (P#1 cpuset 0x0000ffff,,0x0) at Package (cpuset 0x000000ff,0xffffffff,0xffffffff)
* coming from: windows:GetLogicalProcessorInformation:ProcessorGroup
*
* The following FAQ entry in the hwloc documentation may help:
*   What should I do when hwloc reports "operating system" warnings?
* Otherwise please report this error message to the hwloc user's mailing list,
* along with any relevant topology information from your platform.
*
* hwloc will now ignore this invalid topology information and continue.
****************************************************************************

HWLOC seems to be working fine and allowing the software to run on all logical processors or on a selected logical processor. 

[topology.txt](https://github.com/open-mpi/hwloc/files/7508413/topology.txt)

Does this warning message signify any error? 
How do we resolve it and is there a way to mute this warning message from showing up in stdout/stderr.

**Comment by bgoglin** [comment]
Hello
There's an issue with these recent processors because old windows versions are not able to report the affinity of NUMA nodes with so many cores. The Windows API was updated very recently to report NUMA node spanning multiple processor groups. If you have windows 11 or windows 10 build 20348, try the tarball from https://ci.inria.fr/hwloc/job/extended-customPR/ (it's a pull request that I opened today but could not test on a large windows 11 machine yet).

**Comment by rppendya** [comment]
Hello Brice,

Thanks for the information. I am trying to get access to a windows 11 machine. Please let me know when your pull request gets merged.
In the mean time, is there a way to suppress HWLOC messages from printing to stdout/stderr

**Comment by bgoglin** [comment]
Set the environment variable HWLOC_HIDE_ERRORS=1 to hide those messages. Beware that even if hwloc seems to be working fine, the topology is wrong on the NUMA side. It shows 2 NUMA nodes per packages (one with 32 cores and one with 4 cores) while there's actually only one.

**Comment by bgoglin** [comment]
Which windows 10 release are you running on this machine? (should be at the bottom of system information). If you're not sure, just try lstopo from the zipball at the link above, we'll see if it still warns.

**Comment by rppendya** [comment]
I have the following version 19043.1023

**Comment by rppendya** [comment]
Hi Brice, 

Our software uses libhwloc-*.dll. I enabled the environment variable HWLOC_HIDE_ERRORS=1. But, I still see the above mentioned error.

My test system can't be upgraded to windows 11. I am figuring out another way to test your pull request

**Comment by rppendya** [comment]
I got a windows server 2022 installed on the same system and ran our software. I still encounter the same warning message.

Here is the OS info I tested with
Edition	Windows Server 2022 Standard Evaluation
Version	21H2
Installed on	‎11/‎11/‎2021
OS build	20348.169

Here is the warning message I received
****************************************************************************
* hwloc PR-496-20211109.0944.git189ea79ac received invalid information from the operating system.
*
* Failed with: intersection without inclusion
* while inserting Group0 (P#1 cpuset 0x0000ffff,,0x0) at Package (cpuset 0x000000ff,0xffffffff,0xffffffff)
* coming from: windows:GetLogicalProcessorInformation:ProcessorGroup
*
* The following FAQ entry in the hwloc documentation may help:
*   What should I do when hwloc reports "operating system" warnings?
* Otherwise please report this error message to the hwloc user's mailing list,
* along with any relevant topology information from your platform.
*
* hwloc will now ignore this invalid topology information and continue.
****************************************************************************

**Comment by bgoglin** [comment]
We discussed the issue with one of your colleague. The NUMA affinity issue is fixed in the PR if using a recent Windows (your WS2022 looks good). The L3 affinity was wrong too, again because of the Windows API. It is being fixed in Windows and I added support that new API in the PR, but it's not documented when it'll be implemented in actual Windows releases.

The remaining warning comes from Windows processor groups spanning across both socket. This seems strange to me but I don't know if that's expected or not. All this Windows support for Packages with more than 64 hyperthreads in slowly being implemented and released, maybe processor groups will get fixed too.

HWLOC_HIDE_ERRORS should actually be set to 2 instead of 1 to remove this warning.

**Comment by rppendya** [comment]
Hi Brice,

To understand the problem little bit better, I enabled debug messages in hwloc library and ran our software on high core count machine again. I am only showing the debug messages related to warning messages.

querying windows processor groups
found 3 windows processor groups
Found 3 active windows processor groups
group 0 with 64 cpus mask 0xffffffffffffffff
group 0 64 bitmap 0xffffffff,0xffffffff
group 1 with 16 cpus mask 0xffff
group 1 16 bitmap 0x0000ffff,,0x0
group 2 with 64 cpus mask 0xffffffffffffffff
group 2 64 bitmap 0xffffffff,0xffffffff,,,,0x0
CPU phase discovery...
CPU phase discovery in component windows...
Package#4294967295 0: mask 0:ffffffff
Package#4294967295 1: mask 1:ff
Package#4294967295 bitmap 0x000000ff,0xffffffff,0xffffffff
Package#4294967295 0: mask 1:ff00
Package#4294967295 1: mask 2:ffffffff
Package#4294967295 bitmap 0xffffffff,0xffffffff,,0x0000ff00,,0x0

NUMANode#0 0: mask 0:ffffffff
NUMANode#0 1: mask 1:ff
NUMANode#0 bitmap 0x000000ff,0xffffffff,0xffffffff
NUMANode#1 0: mask 2:ffffffff
NUMANode#1 1: mask 1:ff00
NUMANode#1 bitmap 0xffffffff,0xffffffff,,0x0000ff00,,0x0
group 0 64 cpus mask ffffffff
group 0 64 bitmap 0xffffffff,0xffffffff
group 1 16 cpus mask ffff
group 1 16 bitmap 0x0000ffff,,0x0
****************************************************************************
* hwloc 2.7.0a1 received invalid information from the operating system.
*
* Failed with: intersection without inclusion
* while inserting Group0 (P#1 cpuset 0x0000ffff,,0x0) at Package (cpuset 0x000000ff,0xffffffff,0xffffffff)
* coming from: windows:GetLogicalProcessorInformation:ProcessorGroup
*
* The following FAQ entry in the hwloc documentation may help:
*   What should I do when hwloc reports "operating system" warnings?
* Otherwise please report this error message to the hwloc user's mailing list,
* along with any relevant topology information from your platform.
* 
* hwloc will now ignore this invalid topology information and continue.
****************************************************************************
group 2 64 cpus mask ffffffff
group 2 64 bitmap 0xffffffff,0xffffffff,,,,0x0


What is it in the processor group of this machine that HWLOC doesn't like? There are 3 processor groups and their bitmasks look correct (group1 spawns between two packages).

**Comment by bgoglin** [comment]
Yes, hwloc correctly parses the windows processor groups, but I am not sure whether windows is supposed to create processor groups than spans between packages like this. Processor groups are described as scheduling entities where you assign threads. Having a group with a part of a processor and a part of another means than assigning a thread to that group would be strange from a locality and scheduling point of view. The thread would not be allowed to move to all cores of its current package, but it would be allowed to move to a core of another processor.
I would like to ask Microsoft if this is the intended behavior but I don't know where to ask. If Microsoft says this is the intended behavior, I'll remove "processor groups" from the hwloc topology.

**Comment by bgoglin** [comment]
I managed to get an answer from Microsoft: the behavior is expected. groups are odd but it's not very important anymore because the scheduling constraints of processor groups have been reduced in WS2022.
So I am thinking of removing the processor groups from the hwloc topology (or maybe configurable with an environment variable) but keep them in the windows specific API that we added in https://github.com/open-mpi/hwloc/pull/452
Maybe @ivankochin has an opinion

**Comment by rppendya** [comment]
Thanks Brice.  This discussion is very helpful for us in understanding how HWLOC treats high core count machine. Once you figure out how to resolve this issue, can you also please consider doing a release/tag of HWLOC with these fixes or let me know when you intend to do it

**Comment by ivankochin** [comment]
@bgoglin removing the groups from the topology looks like a good idea!

> the scheduling constraints of processor groups have been reduced in WS2022.

Could you please clarify what is WS2022?

**Comment by bgoglin** [comment]
@ivankochin here's what I got from Microsoft: we’ve also made changes in WS2022 which make it less necessary to deal with them.  By default now, processes are multigroup aware so while processes still have a “primary” group which is used to keep legacy API’s consistent, unless you explicitly become multigroup aware by calling various affinity API’s to cross groups, threads in a process will fan out to use all the cpu’s on the system as necessary rather than being restricted to a single group by default.

**Comment by bgoglin** [comment]
@ivankochin By the default, I am not talking about removing the API that we added a couple releases ago to query windows processor groups. I am only talking about not making "Group" objects in the topology for processor groups anymore.

**Comment by ivankochin** [comment]
> @ivankochin By the way, I am not talking about removing the API that we added a couple releases ago to query windows processor groups. I am only talking about not making "Group" objects in the topology for processor groups anymore.

Yes, thanks, I understood it.

WS2022 most likely means Windows Server 2022.

**Comment by bgoglin** [comment]
> WS2022 most likely means Windows Server 2022.

Indeed.

**Comment by bgoglin** [comment]
@rppendya Try a zip from https://ci.inria.fr/hwloc/job/bgoglin/451/, the warning should be gone without having to set HWLOC_HIDE_ERRORS=2 in the environment. And then please try setting HWLOC_WINDOWS_PROCESSOR_GROUP_OBJS=1 to verify that the warning comes back (this reenables the groups that I disabled by default). Thanks.

**Comment by rppendya** [comment]
@bgoglin I tried the zip. Warning went away by default and was re-enabled using the above environment variable. 
But, I see a different problem now. If the environment variable isn't set, our software is detecting wrong number of cores in the system (It detected 16 cores once and 8 cores at another time). But, it accurately detects 72 cores if the environment variable is set

**Comment by bgoglin** [comment]
Yes, I also noticed the issue here. I fixed my commit and the new ZIP should be ready at https://ci.inria.fr/hwloc/job/bgoglin/452/ within 5 or 10 minutes.

**Comment by rppendya** [comment]
@bgoglin, It works as it is supposed to now. Thanks for the fix

**Comment by ChengChen002** [comment]
The same problem persists when I set "hwloc_topology_set_type_filter(topology, HWLOC_OBJ_GROUP, HWLOC_TYPE_FILTER_KEEP_STRUCTURE);". Is this expected?

**Comment by bgoglin** [comment]
> The same problem persists when I set "hwloc_topology_set_type_filter(topology, HWLOC_OBJ_GROUP, HWLOC_TYPE_FILTER_KEEP_STRUCTURE);". Is this expected?

Hello
Please open a new issue and report there what's asked in the template (hardware, operatin system, etc). This issue was very specific to windows on some large CPUs, but similar warnings can appear for many different reasons.
Brice

**Comment by ChengChen002** [comment]
Same operating system and hardware, same hwloc version and exactly the same warning message. I am not sure if I need open a new issue for  this.

**Comment by bgoglin** [comment]
OK. HWLOC_TYPE_FILTER_KEEP_STRUCTURE is not supposed to avoid warnings because it removes "useless" groups, which means groups that are identical to other hierarchy objects. The warning above comes from "strange" processor groups exposed by windows, those are not identical to existing objects, and even worse they are conflicting with other objects, that's why hwloc warns.
Did you try with a more recent hwloc version? This issue is supposed to be fixed in hwloc 2.7.0 which basically disables those processor groups. That fix may be reverted by setting HWLOC_WINDOWS_PROCESSOR_GROUP_OBJS=1, so the warning should come back in this case.

**Comment by bgoglin** [comment]
HWLOC_TYPE_FILTER_KEEP_NONE should avoid the warning since Groups are totally ignored in that case, but you may also miss other useful Groups (Groups can be used for many locality things that aren't just Cores, Dies, Packages, etc). Usually not a good idea.
